=== andrewismoody/FRC3680_Java/schema/auto.schema.json
{
    "$id": "auto.schema.json",
    "$schema": "https://json-schema.org/draft-07/schema",
    "description": "Schema to define auto actions for a particular season",
    "type": "object",
    "required": [ "season", "version", "description", "poses", "groups", "locations", "positions", "actions", "events", "targets", "fixtures", "sequences" ],
    "additionalProperties": false,
    "properties": {
      "$schema": {
        "type": "string",
        "description": "The schema version this file adheres to"
      },
      "season": {
        "type": "string",
        "description": "The season this auto definition is for"
      },
      "version": {
        "type": "string",
        "description": "The version of the auto definition"
      },
      "description": {
        "type": "string",
        "description": "A description of this auto definition"
      },
      "params": {
        "$ref": "params.schema.json"
      },
      "poses": {
        "type": "array",
        "description": "Definitions of poses that will be referenced by events and actions",
        "items": {
          "$ref": "pose.schema.json"
        },
        "minItems": 1
      },
      "groups": {
        "type": "array",
        "description": "Group labels that will be referenced by poses",
        "items": {
          "type": "string"
        },
        "minItems": 1
      },
      "travelGroups": {
        "type": "array",
        "description": "Group labels that are specifically used for travelling, not positioning (like waypoints)",
        "items": {
          "type": "string"
        },
        "minItems": 1
      },
      "locations": {
        "type": "array",
        "description": "Location labels that will be referenced by poses",
        "items": {
          "type": "string"
        },
        "minItems": 1
      },
      "positions": {
        "type": "array",
        "description": "Position labels that will be referenced by poses",
        "items": {
          "type": "string"
        },
        "minItems": 1
      },
      "actions": {
        "type": "array",
        "description": "Action labels that will be referenced by poses",
        "items": {
          "type": "string"
        },
        "minItems": 1
      },
      "fixtures": {
        "type": "array",
        "description": "Definitions of field fixtures that may be interacted with during auto",
        "items": {
          "$ref": "fixture.schema.json"
        },
        "minItems": 1
      },
      "events": {
        "type": "array",
        "description": "Definitions of events that will trigger targets",
        "items": {
          "$ref": "event.schema.json"
        },
        "minItems": 1
      },
      "targets": {
        "type": "array",
        "description": "Definitions of targets to be pursued during auto",
        "items": {
          "$ref": "target.schema.json"
        },
        "minItems": 1
      },
      "sequences": {
        "type": "array",
        "description": "Definitions of sequences of events to be executed during auto",
        "items": {
          "$ref": "sequence.schema.json"
        },
        "minItems": 1
      }
    }
  }

=== andrewismoody/FRC3680_Java/src/main/deploy/auto2025.json
{
    "$schema": "../../../schema/auto.schema.json",
    "season": "2025",
    "version": "1.0.0",
    "description": "Autonomous routine for 2025 season",
    "groups": [
        "any",
        "stage",
        "score",
        "pickup",
        "start",
        "travel",
        "alignLeft",
        "alignRight",
        "align",
        "approachLeft",
        "approachRight",
        "approach",
        "idle",
        "none"
    ],
    "locations": [
        "any",
        "reef",
        "processor",
        "coral",
        "barge",
        "adHoc",
        "waypoint",
        "tag",
        "interest",
        "none"
    ],
    "positions": [
        "any",
        "ground",
        "trough",
        "lower",
        "middle",
        "upper",
        "processor",
        "none"
    ],
    "actions": [
        "any",
        "drop",
        "pop",
        "pickup",
        "raise"
    ],
    "fixtures": [
        {
            "type": "tag",
            "index": 12,
            "translation": {
                "position": [33.51, 25.80, 0],
                "rotation": 54
            }
        },
        {
            "type": "tag",
            "index": 13,
            "translation": {
                "position": [33.51, 291.20, 0],
                "rotation": 306
            }
        },
        {
            "type": "tag",
            "index": 17,
            "translation": {
                "position": [160.39, 130.17, 0],
                "rotation": 240
            }
        },
        {
            "type": "tag",
            "index": 18,
            "translation": {
                "position": [144, 158.50, 0],
                "rotation": 180
            }
        },
        {
            "type": "tag",
            "index": 19,
            "translation": {
                "position": [160.39, 186.83, 0],
                "rotation": 120
            }
        },
        {
            "type": "tag",
            "index": 20,
            "translation": {
                "position": [193.10, 186.83, 0],
                "rotation": 60
            }
        },
        {
            "type": "tag",
            "index": 21,
            "translation": {
                "position": [209.49, 158.50, 0],
                "rotation": 0
            }
        },
        {
            "type": "tag",
            "index": 22,
            "translation": {
                "position": [193.10, 130.17, 0],
                "rotation": 300
            }
        }
    ],
    "poses": [
        {
            "name": "start_1",
            "group": "start",
            "location": "tag",
            "index": 12,
            "position": "ground",
            "action": "none"
        }
    ],
    "events": [
        {
            "name": "Await Pose Start 1",
            "type": "await",
            "pose": "start_1",
            "parallel": false
        }
    ],
    "targets": [
        {
            "module": "drive",
            "group": "start",
            "location": "start",
            "index": 1,
            "fixture": {
                "type": "start",
                "index": 1
            }
        }
    ],
    "sequences": [
        {
            "name": "Auto Routine 1",
            "events": [
                "Await Pose Start 1"
            ]
        }
    ]
}

=== andrewismoody/FRC3680_Java/schema/example.json
{
    "$schema": "auto.schema.json",
    "season": "2025",
    "version": "1.0.0",
    "description": "Example autonomous routine for the 2025 season",
    "groups": [
        "start",
        "pickup",
        "score"
    ],
    "locations": [
        "start",
        "waypoint",
        "score"
    ],
    "positions": [
        "ground",
        "trough",
        "lower"
    ],
    "actions": [
        "pickup",
        "drop"
    ],
    "poses": [
        {
            "name": "start1",
            "group": "start",
            "location": "start",
            "index": 1,
            "position": "ground",
            "action": "pickup"
        }
    ],
    "events": [
        {
            "name": "Open_Latch",
            "type": "time",
            "parallel": false,
            "milliseconds": 2000,
            "triggerType": "boolean",
            "triggerValueBool": true,
            "triggerModule": "latch"
        }
    ],
    "targets":[
        {
            "module": "latch",
            "position": "upper",
            "measurement": 28.8
        },
        {
            "module": "drive",
            "group": "pickup",
            "location": "source",
            "index": 1,
            "fixture": {
                "type": "tag",
                "index": 5
            }
        }
    ],
    "fixtures": [
        {
            "type": "tag",
            "index": 5,
            "translation": {
                "position": [100.0, 50.0, 0.0],
                "rotation": 1.57
            }
        },
        {
            "type": "reef",
            "index": 1,
            "derivedFrom": {
                "fixture": {
                    "type": "tag",
                    "index": 5
                },
                "function": "parallel",
                "offset": 5.0
            }
        },
        {
            "type": "scoring",
            "index": 1,
            "derivedFrom": {
                "derivedFrom": {
                    "fixture": {
                        "type": "reef",
                        "index": 1
                    },
                    "function": "none"
                },
                "function": "parallel",
                "offset": 10.0
            }
        },
        {
            "type": "approach",
            "index": 1,
            "derivedFrom": {
                "derivedFrom": {
                    "fixture": {
                        "type": "reef",
                        "index": 1
                    },
                    "fixture2":{
                        "type": "reef",
                        "index": 2
                    },
                    "function": "bisector"
                },
                "function": "perpendicular",
                "offset": 10.0
            }
        }
    ],
    "sequences": [
        {
            "name": "Start_to_Pickup",
            "events": [
                "Open_Latch"
            ]
        }
    ]
}
